### ISSUE TITLE
How to get model checkpoints files?

### ISSUE THREAD

**Issue by Lu-Tan** [AnanyaKumar/transfer_learning#4]
Thank you for this great job !
When I try to run expriments on my own device, I don't know where to get the checkpoint of pretrained models. For example, in fmow.yaml, the checkpoint_path is specified as '/u/scr/ananya/simclr_weights/mocotp_checkpoint_0200.pth.tar'. But I'm confused where to get this pth.tar file ? 
Actually I found one checkpoint from https://github.com/facebookresearch/moco but it is pretrained on ImageNet. However, to reproduce LP results on FMoW, it seems that the checkpoint pretrained on unlabeled FMoW is needed. Could you provide the checkpoint?
Thanks !

**Comment by AnanyaKumar** [comment]
Sorry for the delayed reply - you can find the pretrained checkpoints here: https://worksheets.codalab.org/bundles/0x57abca4a55ec4f7e9908098beb2633c6
